# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf09baa907cfc64ad72e18c12fcc6886980db9c4485cde9038051aceb885c4b0cd59c107f2e1b094e7edbcf2803423483b572fd0de1a883c51fb613677dfaf10

test:
  secret_key_base: 697d1c6ff58605eb65f43599bc4430c8b432202e49f64da9a15ea48de718137afc6b3a3077ad1b0ead29a17f55f9b4c37ec827a659d9df78f2193b561088aac6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
